[package]
name = "sharedcockpit"
version = "0.1.0"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4"
crossbeam-channel = "0.4"
csv = "1.1"
indexmap = {version = "1.5", features = ["serde-1"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
simconnect = "0.1"
text_io = "0.1"