[package]
name = "sharedcockpit"
version = "0.1.0"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
simconnectsdk = {path="../simconnectsdk"}
serde_json = "1.0"
crossbeam-channel = "0.4"