[workspace]
members = [
    "src/yourcontrols",
    "src/yourcontrols-net",
    "src/yourcontrols-types",
    "src/yourcontrols-hoster",
    "src/yourcontrols-discord"
]

default-members = ["src/yourcontrols"]