[package]
name = "yourcontrols"
version = "2.4.0"
license = "GPL-3.0"
repository = "https://github.com/Sequal32/yourcontrols"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"

[[bin]]
name = "YourControls"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
attohttpc = {version = "0.16", features = ["json"]}
base64 = "0.13"
bimap = {version = "0.5", features = ["serde"]}
byteorder = "1.3"
crossbeam-channel = "0.4"
dns-lookup = "1.0"
igd = "0.12"
indexmap = {version = "1.6", features = ["serde-1"]}
laminar = "0.4"
local_ipaddress = "0.1"
log = "0.4"
num = "0.3"
retain_mut = "0.1"
rmp-serde = "0.15"
semver = "0.11"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
simconnect = "0.1.3"
simplelog = "0.9"
spin_sleep = "1.0"
tungstenite = "0.11.1"
util = "0.1.2"
web-view = "0.6"
zip = "0.5"

[build-dependencies]
winres = "0.1"