[package]
name = "sharedcockpit"
version = "0.1.3"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.13"
bimap = "0.5"
byteorder = "1.3"
crossbeam-channel = "0.4"
dns-lookup = "1.0"
igd = "0.11"
indexmap = {version = "1.6", features = ["serde-1"]}
local_ipaddress = "0.1"
# reqwest = {version = "0.10", features = ["blocking", "json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
spin_sleep = "1.0"
simconnect = {path = "../simconnect"}
web-view = { version = "0.6"}