[package]
name = "sharedcockpit"
version = "2.0.0"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.13"
bimap = "0.5"
byteorder = "1.3"
crossbeam-channel = "0.4"
dns-lookup = "1.0"
igd = "0.11"
indexmap = {version = "1.6", features = ["serde-1"]}
local_ipaddress = "0.1"
log = "0.4"
requests = {version = "0.0"}
semver = "0.11"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
simconnect = {path = "../simconnect"}
simplelog = "0.8"
spin_sleep = "1.0"
web-view = "0.6"

[dev-dependencies]
web-view = { version = "0.6", features = ["edge"]}