[package]
name = "sharedcockpit"
version = "0.1.0"
authors = ["Connor T <connor0530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.12"
byteorder = "1.3"
crossbeam-channel = "0.4"
csv = "1.1"
dns-lookup = "1.0"
local_ipaddress = "0.1"
igd = "0.11"
indexmap = {version = "1.6", features = ["serde-1"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
simconnect = "0.1"
web-view = { version = "0.6"}