[package]
name = "yourcontrols-discord"
version = "0.1.0"
authors = ["SafeShows <nils3nils@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/Sequal32/yourcontrols"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "yourcontrols-discord-test"
path = "src/test.rs"

[dependencies]
discord_game_sdk = "1.0.1"
crossbeam-channel = "0.4"
base64 = "0.13.0"

yourcontrols-types = {path = "../yourcontrols-types"}